### ISSUE TITLE
Overflow and termination issue

### ISSUE THREAD

**Issue by wuestholz** [ConsenSysMesh/MultiSigWallet#2]
I noticed an issue in function `getTransactionIds` of the `MultiSigWallet` contract: if the `from` argument is greater than the `to` argument the [subtraction on line 362](https://github.com/ConsenSys/MultiSigWallet/blob/master/MultiSigWalletWithDailyLimit.sol#L362) will overflow, creating a very large array. Independently, this would also result in the subsequent loop not terminating for a very long time.

I would suggest that you add more parameter validation at the beginning of the method body to prevent this (e.g., `require(from <= to)` or `require(from < to)` depending on the intended semantics).

**Comment by maurelian** [comment]
Thanks @wuestholz! I'll pass this on to the Gnosis team, but I don't think we'll take any action here. The primary purpose of this repository is to serve as a marker to record the precise source code and byte code which has been stood the test of time in holding a large amount of funds. 

Also, the worst case scenario appears to be that the function call would run out of gas, and thus not result in any dangerous state changes. Does that ring true to you?

**Comment by wuestholz** [comment]
@maurelian Thanks for looking into this! Yes, it would be great to pass it on to avoid this in future deployments. However, I agree that it's not a critical issue. Otherwise, I would have disclosed it through different channels. Fixing it would mainly help clients by documenting the precondition and, thus, avoid losing gas if the contract is used incorrectly.
